apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app
  type: NodePort
  ports:
    - port: 81
      targetPort: 8080
      nodePort: 30090
